events {}

http {
  upstream kong_dps_http {
    server kong-dp1:8000;
    server kong-dp2:8000;
  }

  upstream kong_dps_https {
    server kong-dp1:8443;
    server kong-dp2:8443;
  }

  server {
    listen 8080;
    server_name apigw.placsoft.local;

    location / {
      proxy_pass http://kong_dps_http;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto http;
    }
  }

  server {
    listen 8443 ssl;
    server_name apigw.placsoft.local;

    ssl_certificate     /etc/nginx/certs/apigw.placsoft.local.crt;
    ssl_certificate_key /etc/nginx/certs/apigw.placsoft.local.key;

    location / {
      proxy_pass https://kong_dps_https;
      proxy_ssl_server_name on;
      proxy_ssl_verify off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}
